<?php

/**
 * Implements hook_menu().
 */
function gsb_hook_xray_menu() {
  $items = array();  
  $items['admin/config/gsb/hook-xray'] = array(
    'title' => 'Hook XRay',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_hook_xray_form'),
    'access arguments' => array('access administration menu'),
  );
  return $items;
}

function gsb_hook_xray_form($form, &$form_state) {

  // get list of drupal 7 core hook names
  $core_hooks = gsb_hook_xray_drupal7_core_hooks::get_hooks_names();

  // get hook info - by hook name
  $results = array();
  foreach($core_hooks as $value) {
    $results[$value] = _gsb_hook_xray_get_hook_info($value);
  }
  dpm($results);
  
  // get hook info - by module name
  $results = _gsb_hook_xray_array_flip_into_subarray($results);
  ksort($results);
  dpm($results);

}

function _gsb_hook_xray_get_hook_info($hook) {
  if (strtolower(substr($hook, 0, 5)) == 'hook_') {
    $hook = substr($hook, 5);
  } elseif (substr($hook, 0, 1) == '_') {
    $hook = substr($hook, 1);
  }
  return module_implements($hook);
}

function  _gsb_hook_xray_array_flip_into_subarray($input) {
  $output = array();
  foreach ($input as $key => $values) {
    foreach ($values as $value) {
      $output[$value][] = $key;
    }
  }
  return $output;
}
